#
# ~/.config/alacritty/alacritty.yml
#

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import:
        - ~/.config/alacritty/env.yml
        - ~/.config/alacritty/window.yml
        - ~/.config/alacritty/scrolling.yml
        - ~/.config/alacritty/font.yml
        - ~/.config/alacritty/colors.yml
        - ~/.config/alacritty/bell.yml
        - ~/.config/alacritty/selection.yml
        - ~/.config/alacritty/cursor.yml
        - ~/.config/alacritty/shell.yml
        - ~/.config/alacritty/mouse.yml
        - ~/.config/alacritty/hints.yml
        - ~/.config/alacritty/bindings.yml
        - ~/.config/alacritty/debug.yml
        - ~/.config/alacritty/themes/nord.yml
