#
# ~/.config/alacritty/env.yml
#

# Any itesmin the `env` entry below will be added as environment variables.
# Some entries may override variables set by alacritty itself.
env:
        # TERM variable
        #
        # This value is used to set the `$TERM` environment variable for each
        # instance of Alacritty. If it is not present, alacritty will check the
        # local terminfo database and use `alacritty` if it is availalbe,
        # otherwise `xterm-256color` is used.
        TERM: alacritty
